// Autogenerated models

export class GardenParameters
{
    temperature: number;
    humidity: number;
    moisture: number;
    isWindowOpen: boolean;
    isPumpOpen: boolean;

    constructor(temperature: number = null,humidity: number = null,moisture: number = null,isWindowOpen: boolean = null,isPumpOpen: boolean = null,)
    {
        this.temperature = temperature;
        this.humidity = humidity;
        this.moisture = moisture;
        this.isWindowOpen = isWindowOpen;
        this.isPumpOpen = isPumpOpen;
    }
}