// Autogenerated models

export class SolarPanelResults
{
    cumulativeEnergy: number;
    cumulativeEnergyEfficiency: number;

    constructor(cumulativeEnergy: number = null,cumulativeEnergyEfficiency: number = null,)
    {
        this.cumulativeEnergy = cumulativeEnergy;
        this.cumulativeEnergyEfficiency = cumulativeEnergyEfficiency;
    }
}